name: Lint, Check Types
on: push

jobs:
  check-types:
    name: Lint, Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: guest-list-mobile/pnpm-lock.yaml
      - run: pnpm install
        working-directory: guest-list-mobile
      - run: pnpm eslint . --max-warnings 0
        working-directory: guest-list-mobile
      - run: pnpm tsc
        working-directory: guest-list-mobile
